#config_version=4
mode:
    start_events: ball_starting
    priority: 100

slide_player:
  mode_base_started:
    widgets:
      - type: text
        text: (score)
        number_grouping: true
        min_digits: 2
        font_size: 100
      - type: text
        text: PLAYER (number)
        y: 10
        x: 10
        font_size: 50
        anchor_x: left
        anchor_y: bottom
      - type: text
        text: BALL (ball)
        y: 10
        x: right-10
        anchor_x: right
        anchor_y: bottom
        font_size: 50
      - type: text
        text: "POTATO VALUE: (potato)"
        y: 40%

scoring:
    s_right_inlane_active:
        score: 100
    s_left_flipper_active:
        score: 1000
        potato: 1
    s_right_flipper_active:
        potato: -2

