#config_version=5
mode:
  start_events: ball_starting
  priority: 100
  code: base.Base

event_player:
  multiplayer_game: player_1_multiplayer_slide
  player_1_ball_started: player_1_multiplayer_slide

slide_player:
  single_player_ball_started: slide_1
  player_1_multiplayer_slide: slide_2
  player_2_ball_started: slide_3
  player_3_ball_started: slide_4
  player_4_ball_started: slide_5

sound_player:

  mode_base_started:
    waiting to plunge loop:
      loops: -1

  sw_plunger:
    waiting to plunge loop:
      action: stop
    base background music:
      loops: -1

  balldevice_elevator_ball_enter:
    base background music:
      loops: -1

  sw_ramp_1: ramp 1
  sw_ramp_2: ramp 2
  shots_standups_lit_hit: standup hit lit
  shots_standups_unlit_hit: standup hit unlit
  sw_slingshot: little metal
  sw_jet: medium metal

variable_player:
  left_orbit_hit:
    score: 1000000
  left_ramp_hit:
    score: 1000000
  side_ramp_hit:
    score: 2000000
  right_ramp_hit:
    score: 1000000
  right_orbit_hit:
    score: 1500000
  center_ramp_hit:
    score: 250000
  sw_slingshot:
    score: 5170
  sw_jet:
    score: 75020
  sw_outlane:
    score: 24440
  sw_inlane:
    score: 47650
  standups_lit_hit:
    score: 10000
  standups_unlit_hit:
    score: 50000
  standups_lit_complete:
    score: 100000
  rollover_lanes_lit_hit:
    score: 5000
  rollover_lanes_unlit_hit:
    score: 45000
  rollover_lanes_lit_complete:
    score: 375000
  sw_small_car_crash:
    score: 25000
  sw_big_car_crash:
    score: 11000
  balldevice_lower_vuk_ball_enter:
    score: 475000
  balldevice_upper_vuk_ball_enter:
    score: 110000
  balldevice_retina_hole_ball_enter:
    score: 225000

shot_groups:
  rollover_lanes:
    shots: left_lane, middle_lane, right_lane
    rotate_left_events: sw_left_flipper
    rotate_right_events: sw_right_flipper
  standups:
    shots: standup_1, standup_2, standup_3, standup_4, standup_5

slides:
  slide_1:
  - type: text
    text: (player1|score)
    number_grouping: true
    min_digits: 2
    y: middle+2
      #persist_slide: yes
    style: tall_title
  - type: text
    text: BALL (player1|ball)    (machine|credits_string)
    anchor_y: bottom
    style: small
    y: bottom+1

  slide_2:
  - type: text
    text: (player1|score)
      #font: medium
    number_grouping: true
    min_digits: 2
    anchor_y: top
    anchor_x: right
    x: right-60
    y: top-2
  - type: text
    text: (player2|score)
    style: medium
    anchor_y: top
    anchor_x: right
    number_grouping: true
    min_digits: 2
    x: right-2
    y: top-2
  - type: text
    text: (player3|score)
    style: medium
    anchor_y: bottom
    anchor_x: right
    y: bottom+10
    x: right-60
    number_grouping: true
    min_digits: 2
  - type: text
    text: (player4|score)
    style: medium
    anchor_y: bottom
    anchor_x: right
    y: bottom+10
    x: right-2
    number_grouping: true
    min_digits: 2
  - type: text
    text: BALL (player1|ball)    (machine|credits_string)
    anchor_y: bottom
    style: small
    y: bottom+1

  slide_3:
  - type: text
    text: (player1|score)
    style: medium
    number_grouping: true
    min_digits: 2
    anchor_y: top
    anchor_x: right
    x: right-60
    y: top-2
  - type: text
    text: (player2|score)
#      font: medium
    anchor_y: top
    anchor_x: right
    number_grouping: true
    min_digits: 2
    x: right-2
    y: top-2
  - type: text
    text: (player3|score)
    style: medium
    anchor_y: bottom
    anchor_x: right
    y: bottom+10
    x: right-60
    number_grouping: true
    min_digits: 2
  - type: text
    text: (player4|score)
    style: medium
    anchor_y: bottom
    anchor_x: right
    y: bottom+10
    x: right-2
    number_grouping: true
    min_digits: 2
  - type: text
    text: BALL (player2|ball)    (machine|credits_string)
    anchor_y: bottom
    style: small
    y: bottom+1

  slide_4:
  - type: text
    text: (player1|score)
    style: medium
    number_grouping: true
    min_digits: 2
    anchor_y: top
    anchor_x: right
    x: right-60
    y: top-2
  - type: text
    text: (player2|score)
    style: medium
    anchor_y: top
    anchor_x: right
    number_grouping: true
    min_digits: 2
    x: right-2
    y: top-2
  - type: text
    text: (player3|score)
#      font: medium
    anchor_y: bottom
    anchor_x: right
    y: bottom+10
    x: right-60
    number_grouping: true
    min_digits: 2
  - type: text
    text: (player4|score)
    style: medium
    anchor_y: bottom
    anchor_x: right
    y: bottom+10
    x: right-2
    number_grouping: true
    min_digits: 2
  - type: text
    text: BALL (player3|ball)    (machine|credits_string)
    anchor_y: bottom
    style: small
    y: bottom+1

  slide_5:
  - type: text
    text: (player1|score)
    style: medium
    number_grouping: true
    min_digits: 2
    anchor_y: top
    anchor_x: right
    x: right-60
    y: top-2
  - type: text
    text: (player2|score)
    style: medium
    anchor_y: top
    anchor_x: right
    number_grouping: true
    min_digits: 2
    x: right-2
    y: top-2
  - type: text
    text: (player3|score)
    style: medium
    anchor_y: bottom
    anchor_x: right
    y: bottom+10
    x: right-60
    number_grouping: true
    min_digits: 2
  - type: text
    text: (player4|score)
#      font: medium
    anchor_y: bottom
    anchor_x: right
    y: bottom+10
    x: right-2
    number_grouping: true
    min_digits: 2
  - type: text
    text: BALL (player4|ball)    (machine|credits_string)
    anchor_y: bottom
    style: small
    y: bottom+1

show_player:
  left_orbit_unlit_hit:
    left orbit: {}

shots:
  left_lane:
    switch: s_left_rollover
    show_tokens:
      light: l_left_rollover
  middle_lane:
    switch: s_center_rollover
    show_tokens:
      light: l_middle_rollover
  right_lane:
    switch: s_right_rollover
    show_tokens:
      light: l_right_rollover
  standup_1:
    switch: s_standup_1
    show_tokens:
      light: l_standup_1
  standup_2:
    switch: s_standup_2
    show_tokens:
      light: l_standup_2
  standup_3:
    switch: s_standup_3
    show_tokens:
      light: l_standup_3
  standup_4:
    switch: s_standup_4
    show_tokens:
      light: l_standup_4
  standup_5:
    switch: s_standup_5
    show_tokens:
      light: l_standup_5
  center_ramp:
    switch: s_center_ramp
