Mode:
    start_events: ball_starting
    stop_events: timer_skill_shot_complete, shot_rightRamp
    priority: 300

Timers:
    skillshot:
        start_value: 10
        tick_interval: 1.5s
        direction: down
        end_value: 0
        control_events:
          - event: sw_subway_enter #Uses this event here because you select Skill Shot from the ball start menu
            action: start

Scoring:
    shot_rightRamp:
        Score: 100000000

Show_Player:
    mode_skillshot_started:
      - show: flash_right_ramp
        repeat: yes
        tocks_per_sec: 4
    mode_skillshot_stopped:
      - show: flash_right_ramp
        action: stop

Slide_Player:
    timer_skillshot_tick:
        type: text
        text: "SKILL SHOT TIME: %ticks"
