# config_version=4
mode:
  start_events: ball_starting
  stop_events: start_mode1_acmag
  priority: 200

logic_blocks:
  accruals:
    enable_the_claw:
      events: mode_claw_lit_for_major_mode_started
      events_when_complete: light_claw
    start_acmag:
      events: sw_acmag
      events_when_complete: start_mode1_acmag

slide_player:
  balldevice_elevator_ball_enter: slide_13
slides:
  slide_13:
  - type: text
    text: PICK YOUR MODE
show_player:
  mode_claw_lit_for_major_mode_started:
    flash:
      lights: l_claw_ready, l_right_ramp_arrow
      key: claw_lit
      speed: 5
      loops: -1
  balldevice_elevator_ball_enter:
    claw_lit:
      action: stop

